name: ad_hoc_ident_example
description: "The example app for the ad_hoc_ident framework. 
Showcases the integration of the framework components."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  rxdart: ^0.28.0

  ad_hoc_ident: ^0.0.1-preview-1
  ad_hoc_ident_util_flutter: ^0.0.1-preview-1
  ad_hoc_ident_util_crypto: ^0.0.1-preview-2
  ad_hoc_ident_util_readable_pseudonym: ^0.0.1-preview-1
  ad_hoc_ident_nfc: ^0.0.1-preview-1
  ad_hoc_ident_nfc_detect_emv: ^0.0.1-preview-1
#  ad_hoc_ident_nfc_scanner_flutter_nfc_kit: ^0.0.1-preview-1
  ad_hoc_ident_nfc_scanner_nfc_manager: ^0.0.1-preview-1
  ad_hoc_ident_ocr: ^0.0.1-preview-1
#  ad_hoc_ident_ocr_camera: ^0.0.1-preview-1 # Import with camera_android below to use nv21 format
  ad_hoc_ident_ocr_camerawesome: ^0.0.1-preview-1
  ad_hoc_ident_ocr_parse_mrz: ^0.0.1-preview-1
  ad_hoc_ident_ocr_extract_google: ^0.0.1-preview-1
#  ad_hoc_ident_ocr_extract_tesseract: ^0.0.1-preview-1 # Note the assets below

  # Import camera_android to use nv21 image format for ocr
  # when using the ad_hoc_ident_ocr_camera package
#  camera_android: ^0.10.9+11


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # The asset folders required for tesseract/flutter_vision:
#  assets:
#    - assets/
#    - assets/tessdata/
